version: '3'

services:
  client:
    build:
      context: ./client
      dockerfile: ./Dockerfile
    ports:
      - "5173:5173"
    environment:
      - VITE_BACKEND_URL=http://localhost:4000/
    # volumes:
    #   - ./client:/app
    depends_on:
      - server

  server:
    build:
      context: ./server
      dockerfile: ./Dockerfile
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=production
    # volumes:
    #   - ./server:/app